config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers => {:registrations => "registrations"}
  resources :listings do 
    resources :contact_owner, only: [:create]
  end

  get 'contact', to: 'pages#contact'
  get "seller", to: 'listings#seller'
 
  root to: 'pages#home'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :listings
end

app/models/listing.rb
class Listing < ApplicationRecord
    has_attached_file :image, styles: { medium: "600x400#", thumb: "100x100" }, default_url: "thumb.jpg"
    validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/

    validates :name, :description, :price, :category, :country, presence: true
    validates :price, numericality: { greater_than: 0 }

    validates_attachment_presence :image

    belongs_to :user
    belongs_to :category

end

app/models/user.rb
class User < ApplicationRecord
  has_many :listings, dependent: :destroy

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  validates :name, presence: true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  protect_from_forgery with: :exception
  include SetCopyright

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
    devise_parameter_sanitizer.permit(:account_update, keys: [:name])
  end

end

app/controllers/concerns/set_copyright.rb
module SetCopyright
  extend ActiveSupport::Concern
  
  included do
    before_action :set_copyright
  end

  def set_copyright
    @copyright = Renderer.copyright 'Marketplace', 'All rights reserved'
  end

  
  class Renderer
    def self.copyright name, msg
      "&copy; #{Time.now.year} | <b>#{name}</b> #{msg}".html_safe
    end
  end
end

app/controllers/contact_owner_controller.rb
class ContactOwnerController < ApplicationController

def create
  @listing = Listing.find(params[:listing_id])
  opts = {
    name: params[:name],
    email: params[:email],
    subject: params[:subject],
    message: params[:message]
  }
  UserMailer.contact_listing_owner(@listing, opts).deliver_later
end


end

app/controllers/listings_controller.rb
class ListingsController < ApplicationController
  before_action :set_listing, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destroy, :seller]
  before_action :check_user, only: [:edit, :update, :destroy]

  # GET /listings
  # GET /listings.json
  def seller
    @listings = Listing.where(user: current_user).order("created_at DESC")
  end

  def index
    @categories = Category.all.map{|c| [ c.category, c.id ] }
    if !params[:category_id].blank?
      @listings = Listing.where(category_id: params[:category_id]).order("created_at DESC")
      @search_parameter = Category.find(params[:category_id]).category
    else
      @listings = Listing.all.order("created_at DESC")
    end
  end

  # GET /listings/1
  # GET /listings/1.json
  def show
  end

  # GET /listings/new

  def new 
    @listing = Listing.new
    @categories = Category.all.map{|c| [ c.category, c.id ] }
  end

  # GET /listings/1/edit
  def edit
    @categories = Category.all.map{|c| [ c.category, c.id ] }
  end

  # POST /listings
  # POST /listings.json
  def create
    @listing = Listing.new(listing_params)
    @listing.category_id = params[:category_id]
    @listing.user_id = current_user.id

    respond_to do |format|
      if @listing.save
        UserMailer.listing_confirmation_email(@listing).deliver_later
        format.html { redirect_to @listing, notice: 'Listing was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  # PATCH/PUT /listings/1
  # PATCH/PUT /listings/1.json
  def update
    @listing.category_id = params[:category_id]
    respond_to do |format|
      if @listing.update(listing_params)
        format.html { redirect_to @listing, notice: 'Listing was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  # DELETE /listings/1
  # DELETE /listings/1.json
  def destroy
    @listing.destroy
    respond_to do |format|
      format.html { redirect_to listings_url, notice: 'Listing was successfully destroyed.' }
    end
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_listing
      @listing = Listing.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def listing_params
      params.require(:listing).permit(:name, :category, :country, :price, :image, :description, :condition)
    end

    def check_user
      if current_user.id != @listing.user_id
        redirect_to root_url, alert: "Sorry, this listing belongs to someone else"
      end
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def contact
  end

  def home
    @listings = Listing.all.order(created_at: :desc).limit(8)
    @categories = Category.all.map{|c| [ c.category, c.id ] }
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  def new
    super
  end

  def create
    super
  end

  def update
    super
  end
end 

app/helpers/application_helper.rb
module ApplicationHelper

  def flash_class(level)
      case level
          when 'notice' then "alert alert-info fade show"
          when 'success' then "alert alert-success fade show"
          when 'error' then "alert alert-danger fade show"
          when 'alert' then "alert alert-danger fade show"
      end
  end

end

app/helpers/devise_helper.rb
module DeviseHelper
  def devise_error_messages!
    return '' if resource.errors.empty?

    messages = resource.errors.full_messages.map { |msg| content_tag(:li, msg) }.join
    html = <<-HTML
    <div class="alert alert-danger alert-dismissible fade show" role="alert">
      <button type="button" class="close" data-dismiss="alert">
        <span aria-hidden="true">&times;</span>
      </button>
      <strong>
       #{pluralize(resource.errors.count, "error")} must be fixed
      </strong>
      #{messages}
    </div>
    HTML

    html.html_safe
  end
end

app/helpers/listings_helper.rb
module ListingsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Marketplace</title>
  <%= csrf_meta_tags %>

  <script src="https://use.typekit.net/pal5neg.js"></script>
  <script>try{Typekit.load({ async: true });}catch(e){}</script>

  <%= stylesheet_link_tag    'application', 'mdb', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'mdb', 'data-turbolinks-track': 'reload' %>

</head>

<body class="<%= content_for :body_class %>">

  <%= render "shared/application_nav" %>

  <div <% if controller.action_name != 'home' %> class="container padding" <% end %> >
    <%= render "shared/messages" %>
    <%= yield %>

  </div>

  <%= render "shared/application_footer" %>

</body>
</html>

app/views/listings/_contact_modal.html.erb
<div class="modal fade" id="modalContactForm" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
        <div class="modal-dialog cascading-modal" role="document">
            <!--Content-->

            <div class="modal-content">
    
                <!--Header-->
                <div class="modal-header light-blue darken-3 white-text">
                    <h4 class="title"><i class="fa fa-pencil"></i> Contact form</h4>
                    <button type="button" class="close waves-effect waves-light" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <!--Body-->
                <%= form_tag (listing_contact_owner_index_path(@listing)) do %>
                    <!-- /listings/1/contact_owner -->
                    <div class="modal-body mb-0">
                        <div class="md-form form-sm">
                            <i class="fa fa-user prefix"></i>
                            <%= text_field_tag :name, nil, class: 'form-control', placeholder: "Your name" %>
                        </div>
        
                        <div class="md-form form-sm">
                            <i class="fa fa-envelope prefix"></i>
                            <%= email_field_tag :email, nil, class: 'form-control', placeholder: "Your email" %>
                            
                        </div>
        
                        <div class="md-form form-sm">
                            <i class="fa fa-tag prefix"></i>
                            <%= text_field_tag :subject, nil, class: 'form-control', placeholder: "Subject" %>
                        </div>
        
                        <div class="md-form form-sm">
                            <i class="fa fa-pencil prefix"></i>
                            <%= text_area_tag :message, nil, class: 'md-textarea', placeholder: "Your message" %>
                        </div>
        
                        <div class="text-center mt-1-half">
                            <button class="btn btn-info mb-2">Send <i class="fa fa-send ml-1"></i></button>
                        </div>
        
                    </div>
                <% end %>
            </div>
            <!--/.Content-->
        </div>
    </div>
    <!--Modal: Contact form-->

app/views/listings/_form.html.erb
<%= form_with(model: listing, html: { multipart: true }, local: true) do |form| %>
  <% if listing.errors.any? %>
    <div id="error_explanation" class="alert alert-danger alert-dismissable">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <h4><%= pluralize(listing.errors.count, "error") %> prohibited this listing from being saved:</h4>

      <ul>
      <% listing.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :name %>
    <%= form.text_field :name, id: :listing_name, class: "form-control" %>
  </div>


  <div class="form-group">
    <%= form.label :description %>
    <%= form.text_field :description, id: :listing_category, class: "form-control" %>
  </div>

  <div class="form-group form-select" id="happy">
    <%= form.label :condition %>
    <%= form.select :condition, options_for_select([['New'], ['Like New'], ['Used']]), id: :listing_condition, class: "mdb-select colorful-select dropdown-primary form-control" %>
  </div>

  
  <div class="form-group form-select">
    <%= form.label :category %>
    <%= select_tag :category_id, options_for_select(@categories), prompt: "Select One", class: "mdb-select colorful-select dropdown-primary form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :country %>
    <%= form.text_field :country, id: :listing_country, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :price %>
    <%= form.text_field :price, id: :listing_price, class: "form-control" %>
  </div>

  <div class="form-group">
    <label class="btn btn-secondary">
      Upload Image <%= form.file_field :image, style: 'display:none' %>
    </label>
  </div>

  <div class="actions">
    <%= form.submit class: "btn btn-primary" %>
  </div>
<% end %>
<hr>
<%= link_to 'Back', listings_path, class: 'btn btn-sm btn-indigo' %>

app/views/listings/_listing.html.erb
<% if params[:action] == 'seller' %>

  <%= render partial: 'listings_table' %>

<% else %>

  <div class="col-xl-3 col-lg-6 col-md-6 margin-top-15">
    <%= link_to listing do %>
    <div class="card listing-card">
      <div class="view overlay hm-white-slight">

      <%= image_tag listing.image.url(:medium), width: '100%', class: 'cursor' %>

      </div>
      <div class="card-body text-center no-padding">
        <div class="text-muted"><%= listing.category.category %></div>
        <h4 class="card-title"><%= listing.name %></h4>
        <p class="card-text">
        <strong>Location:</strong> <%= listing.country %> <br>
          <div class="card-footer">
            <span class="left"><%= number_to_currency listing.price %></span>
            <% if (user_signed_in?) && (current_user == listing.user) && (params[:action] == 'seller') %>
              <%= link_to 'Edit', edit_listing_path(listing) %> | <%= link_to 'Destroy', listing, method: :delete, data: { confirm: 'Are you sure?' } %>
            <% end %>
          </div>
        </p>
      </div>
    </div>
    <% end %>
  </div>

<% end %>

app/views/listings/_listings_table.html.erb
<%= @listings.each do |listing| %>

  <div class="card">
    <div class="card-body">

        <table class="table table-responsive table-fixed">
          <thead>
            <tr>
              <th>Image</th>
              <th>Name</th>
              <th>Category</th>
              <th>Price</th>
              <th>Action</th>
            </tr>
          </thead>
          
          <tbody>
            <tr>
              <td><%= image_tag listing.image.url, width: '100%' %></td>
              <td><%= listing.name %></td>
              <td><%= listing.category.category %></td>
              <td><%= number_to_currency listing.price %></td>
              <td>
                <button class="btn btn-sm btn-primary dropdown-toggle" type="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Edit </button>
                <div class="dropdown-menu">
                  <%= link_to "View", listing, class: 'dropdown-item' %>
                  <%= link_to "Edit", edit_listing_path(listing), class: 'dropdown-item' %>
                  <div class="dropdown-divider"></div>
                  <%= link_to 'Destroy', listing, method: :delete, data: { confirm: 'Are you sure?' }, class: 'dropdown-item'  %>
                </div>
              </td>
            </tr>
          </tbody>
        </table>
    </div>
  </div>

<% end %>

app/views/listings/edit.html.erb
<h1>Editing Listing</h1>

<%= render 'form', listing: @listing %>

<%= link_to 'Show', @listing %> |
<%= link_to 'Back', listings_path %>

app/views/listings/index.html.erb
<% listings = "All" %>

<% if @listings.present? %>

  <h1><%= @search_parameter || listings %> Listings</h1>

  <%= form_tag('/listings', :method=>:get) do %>
   <%= select_tag :category_id, options_for_select(@categories), class: 'mdb-select colorful-select dropdown-primary side', prompt: "Select Instrument" %>
   <%= submit_tag 'Search', class: 'btn btn-md btn-primary' %>
  <% end %> 

  <hr>

  <div class="row">

    <%= render partial: 'listing', collection: @listings %> 

<% else %>

    <h1>No Listings for <%= @search_parameter %> </h1>

<% end %>

  </div>

<% if user_signed_in? %>

<div class="fixed-action-btn" style="bottom: 60px; right: 24px;">
    <a class="btn-floating btn-lg green" href="<%= new_listing_path %>">
        <%= fa_icon "plus" %>
    </a>
</div>

<% end %>

app/views/listings/new.html.erb
<h1 class="new-listing">New Listing</h1>

<%= render 'form', listing: @listing %>

app/views/listings/seller.html.erb
<div class="row">

<% if current_user.listings.present? %>

<%= render partial: 'listings_table' %>

<% else %>
  
    <H4 class="no-listing"> No Listings Found </H4>

<% end %>

</div>

<% if user_signed_in? %>
  <%= link_to 'New Listing', new_listing_path, class: 'btn btn-primary' %>
<% end %>

app/views/listings/show.html.erb
<%= render partial: 'contact_modal' %>



<div class="row">
  <div class="col-md-6">
    <%= image_tag @listing.image.url, width: '100%', class: 'z-depth-2' %>

    <br/>
    <br/>

    <%= link_to "Back", listings_path, class: 'btn btn-md btn-indigo side listing-back-btn' %>
  </div>


  <div class="col-md-6">

    <h1><%= @listing.name %></h1>

    <h4 class="text-muted"><%= @listing.category.category %></h4>
    <hr>
    <p>
      <strong>Description:</strong>
      <%= @listing.description %>
    </p>

    <p>
      <strong>Location:</strong>
      <%= @listing.country %>
    </p>

    <p>
      <strong>Condition:</strong>
      <%= @listing.condition %>
    </p>

    <p>
      <strong>Price:</strong>
      <%= number_to_currency @listing.price %>
    </p>


    <% if current_user == @listing.user %>

      <p><%= link_to 'Edit', edit_listing_path(@listing) %> </p>

    <% end %>

    <%= link_to "Contact Seller", root_path, class: 'btn btn-primary', 'data-toggle': 'modal', 'data-target': '#modalContactForm' %>

  </div>
</div>

app/views/pages/_listing.html.erb
  <div class="col-xl-3 col-lg-6 col-md-6 margin-top-15">
    <%= link_to listing do %>
    <div class="card listing-card">
      <div class="view overlay hm-white-slight">
  
      <%= image_tag listing.image.url(:medium), width: '100%', class: 'cursor' %>
  
      </div>
      <div class="card-body text-center no-padding">
        <div class="text-muted"><%= listing.category.category %></div>
        <h4 class="card-title"><%= listing.name %></h4>
        <p class="card-text">
          <strong>Location:</strong> <%= listing.country %> <br>
          <div class="card-footer">
              <span class="left"><%= number_to_currency listing.price %></span>
          </div>
        </p>
      </div>
    </div>
    <% end %>
  </div>

app/views/pages/_masthead.html.erb
<div class="jumbo-container">
  <div class="row mb-5">
    <div class="col-md-12">
      <div class="card card-image" style="background-image: url(http://stephendavyviolins.com/wp-content/uploads/2012/10/IMG_3130-2.jpg);">
        <div class="text-white text-center d-flex align-items-center rgba-stylish-strong py-5 px-4">
          <div class="py-5 home-jumbo">
            <h2 class="card-title pt-3 mb-5 font-bold jumbo-header">The Audition Cafe Marketplace</h2>
            <p class="px-5 pb-4 jumbo-subtext">Buy or sell musical instruments and accessories. ZERO fees.</p>
            <!--Blue select-->

            <div class="home-select"> <%= form_tag('/listings', :method=>:get) do %>
              <!-- <label for="category_id">Select Instrument:</label> -->
              <%= select_tag :category_id, options_for_select(@categories), class: 'masthead-select mdb-select colorful-select dropdown-primary side', prompt: "Select Instrument" %>
              <%= submit_tag 'Search', class: 'btn btn-md btn-primary' %>
              <% end %>
            </div>

            <div>
              <p class="sell-button"> Looking to sell? <%= link_to "Click here", new_listing_path %></p>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/pages/contact.html.erb
    

<h1>Contact Us</h1>

<hr>

<div class="modal-body mb-0">
    <div class="md-form form-sm">
        <i class="fa fa-user prefix"></i>
        <%= text_field_tag :name, nil, class: 'form-control', placeholder: "Your name" %>
    </div>

    <div class="md-form form-sm">
        <i class="fa fa-envelope prefix"></i>
        <%= email_field_tag :email, nil, class: 'form-control', placeholder: "Your email" %>

    </div>

    <div class="md-form form-sm">
        <i class="fa fa-tag prefix"></i>
        <%= text_field_tag :subject, nil, class: 'form-control', placeholder: "Subject" %>
    </div>

    <div class="md-form form-sm">
        <i class="fa fa-pencil prefix"></i>
        <%= text_area_tag :message, nil, class: 'md-textarea', placeholder: "Your message" %>
    </div>

    <div class="mt-1-half">
        <button class="btn btn-primary mb-2">Send <i class="fa fa-send ml-1"></i></button>
    </div>

</div>

app/views/pages/home.html.erb
<%= render partial: 'masthead' %>

<div class="latest-listings">
  <h1>Latest Listings</h1>
  <hr>
</div>

<div class="container">
  <div class="row">

    <%= render partial: 'listing', collection: @listings %> 

  </div>

</div>

app/views/shared/_application_footer.html.erb
<footer class="footer">
  <div class="container">
    <span class="text-muted"><%= @copyright %>.</span>
  </div>
</footer>

app/views/shared/_application_nav.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <%= link_to root_path do %>
      <%= image_tag 'logo-sticky.png', class: 'navbar-brand', width: '50px' %>
    <% end %>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo02" aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarTogglerDemo02">
      <div class="navbar-nav mr-auto mt-2 mt-lg-0">
        <%= link_to 'Contact', contact_path, class: 'nav-link nav-item' %>
        <%= link_to 'Listings', listings_path, class: 'nav-link nav-item' %>
      </div>
      <form class="form-inline my-2 my-lg-0">

        <% if user_signed_in? %>
            <div class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="http://example.com" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true"
                      aria-expanded="false">
                 <%= fa_icon "user" %> My Account
              </a>
              <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                <%= link_to "Manage Listings", seller_path , class: 'dropdown-item' %>
                <%= link_to "Sell Item", new_listing_path, class: 'dropdown-item' %>
                <%= link_to "Account Settings", edit_user_registration_path, class: 'dropdown-item' %>
                <%= link_to "Log out", destroy_user_session_path, method: :delete, class: 'dropdown-item' %>

              </div>
            </div>

        <% else %>
          <%= link_to "Login", new_user_session_path, class: 'nav-link nav-item' %>
          <div class="sign-up">
            <button class="btn btn-outline-success" type="button"><%= link_to "Sign Up", new_user_registration_path %> </button>
          </div>
        <% end %>
      </form>
    </div>
  </div>
</nav>

app/views/shared/_messages.html.erb
<% flash.each do |key, value| %>
  <div class="<%= flash_class(key) %>">
    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= value %>
  </div>
<% end %>